version: "3.8"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "3002:3002"
    environment:
      - HOST=0.0.0.0
      - PORT=3002
      - NODE_ENV=development
      - SWAGGER_SERVER=http://localhost:3002/api
      - DB_HOST_MASTER=db_master
      - DB_PORT_MASTER=3306
      - DB_USERNAME_MASTER=root
      - DB_PASSWORD_MASTER=
      - DB_DATABASE_MASTER=crud-demo
      - DB_HOST_SLAVE=db_slave
      - DB_PORT_SLAVE=3308
      - DB_USERNAME_SLAVE=root
      - DB_PASSWORD_SLAVE=
      - DB_DATABASE_SLAVE=crud-demo
    depends_on:
      - db_master
      - db_slave
    networks:
      - test_network

  db_master:
    image: mysql:8.0
    container_name: db_master
    restart: always
    networks:
      - test_network
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: crud-demo
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3307:3306"
    volumes:
      - db_master_data:/var/lib/mysql
      - ./db-config/master/master.cnf:/etc/my.cnf
      - ./db-config/master:/docker-entrypoint-initdb.d
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row --gtid-mode=ON --enforce-gtid-consistency --log-slave-updates --master-info-repository=TABLE

  db_slave:
    image: mysql:8.0
    container_name: db_slave
    networks:
      - test_network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: crud-demo
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3308:3306"
    volumes:
      - db_slave_data:/var/lib/mysql
      - ./db-config/slave/slave.cnf:/etc/my.cnf
      - ./db-config/slave:/docker-entrypoint-initdb.d
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row --gtid-mode=ON --enforce-gtid-consistency --log-slave-updates

volumes:
  db_master_data:
  db_slave_data:

networks:
  test_network:
